name: Build and Release Binaries

on:
  push:
    tags:
      - '*'

  
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.19'

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Build binaries (Linux and Windows)
        run: ./build.sh

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: main
          path: ./main

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: main.exe
          path: ./main.exe
      
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/firmaperu-invoker:${{ github.ref_name }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/firmaperu-invoker:${{ github.ref_name }}
 
  build-rpm:
    needs: build
    runs-on: ubuntu-22.04
    container:
      image: rockylinux:8
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Linux binary
        uses: actions/download-artifact@v4
        with:
          name: main
          path: ./

      - name: Install build dependencies
        run: |
          dnf install -y rpm-build rpmdevtools
          
      - name: Prepare RPM build environment
        run: |
          # Reemplazar la versión en el .spec con el tag actual (sin 'v' inicial si existe)
          VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//') 
          sed -i "s/%define version .*/%define version $VERSION/" ./packaging/rpm/firmaperu-invoker.spec
          
          mkdir -p ~/rpmbuild/{SOURCES,SPECS,BUILD,BUILDROOT,RPMS,SRPMS}
          cp ./packaging/rpm/firmaperu-invoker.spec ~/rpmbuild/SPECS/
          cp ./main ~/rpmbuild/SOURCES/
          cp ./config.properties.example ~/rpmbuild/SOURCES/
          cp -r ./public ~/rpmbuild/SOURCES/
          cp ./packaging/rpm/firmaperu-invoker.service ~/rpmbuild/SOURCES/
      - name: Build RPM package
        run: |
          rpmbuild -bb ~/rpmbuild/SPECS/firmaperu-invoker.spec

      - name: Copy RPM to workspace
        run: |
          mkdir -p ./rpm-output
          find ~/rpmbuild/RPMS/ -name "*.rpm" -exec cp {} ./rpm-output/ \;
      
      - name: Verify RPM package
        run: |
          cd ./rpm-output
          rpm -qip *.rpm || echo "Error al verificar el RPM"
        
      - name: Upload RPM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rpm-package
          path: ./rpm-output/*.rpm

  release:
    needs: [build,build-rpm]
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: write # Permiso para crear releases y subir archivos
    steps:
      - name: Download Linux binary
        uses: actions/download-artifact@v4
        with:
          name: main
          path: ./

      - name: Download Windows binary
        uses: actions/download-artifact@v4
        with:
          name: main.exe
          path: ./
      
      - name: Download RPM package
        uses: actions/download-artifact@v4
        with:
          name: rpm-package
          path: ./rpm-output/

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            ./main
            ./main.exe
            ./rpm-output/*.rpm